import json

pyqs_add = [
    # UP 69,000 Teacher (2019)
    {
        "id": "PYQ-69K-001",
        "exam": "UP_PRT",
        "subject": "Hindi",
        "chapter": "Hindi Grammar",
        "topic": "Varnamala",
        "difficulty": "medium",
        "questionType": "mcq",
        "question": "Which of the following sounds belongs to the 'Murdhanya' (मूर्धन्य) place of articulation?",
        "hindiQuestion": "निम्न में से कौन सी ध्वनि 'मूर्धन्य' (मूर्धा से उच्चरित) है?",
        "options": ["ट (Ṭa) sound group", "च (Ca) sound group", "त (Ta) sound group", "प (Pa) sound group"],
        "hindiOptions": ["ट वर्ग", "च वर्ग (तालव्य)", "त वर्ग (दन्त्य)", "प वर्ग (ओष्ठ्य)"],
        "answer": 0,
        "explanation": "ऋ, ट, ठ, ड, ढ, ण, र, ष मूर्धा से उच्चरित होते हैं (ऋटुरषाणां मूर्धा)।",
        "hindiExplanation": "ऋ, ट, ठ, ड, ढ, ण, र और ष का उच्चारण स्थान मूर्धा है।",
        "sourceType": "pyq",
        "pyqDetails": {"examName": "UP 69,000 Assistant Teacher", "year": 2019, "paper": "General Paper", "officialAnswerKeyRef": "Official Key Q08"},
        "tags": ["pyq", "hindi", "prt_2019"]
    },
    {
        "id": "PYQ-69K-002",
        "exam": "UP_PRT",
        "subject": "Child Development",
        "chapter": "Learning Theories",
        "topic": "Thorndike",
        "difficulty": "medium",
        "questionType": "mcq",
        "question": "Which of the following is considered the 'Secondary Law' of learning according to Thorndike?",
        "hindiQuestion": "थार्नडाइक के अनुसार निम्न में से कौन सा सीखने का गौण (द्वितीयक) नियम है?",
        "options": ["Law of Multiple Response (बहु-प्रतिक्रिया का नियम)", "Law of Readiness", "Law of Exercise", "Law of Effect"],
        "hindiOptions": ["बहु-प्रतिक्रिया का नियम", "तत्परता का नियम (मुख्य)", "अभ्यास का नियम (मुख्य)", "प्रभाव का नियम (मुख्य)"],
        "answer": 0,
        "explanation": "Thorndike's 5 secondary laws are: Multiple response, Attitude/disposition, Partial activity, Analogy/assimilation, Associative shifting.",
        "hindiExplanation": "थार्नडाइक के 5 गौण नियम हैं: बहु-अनुक्रिया, मनोवृत्ति, आंशिक क्रिया, सादृश्यता तथा सहचर्यात्मक रूपांतरण।",
        "sourceType": "pyq",
        "pyqDetails": {"examName": "UP 69,000 Assistant Teacher", "year": 2019, "paper": "General Paper", "officialAnswerKeyRef": "Official Key Q45"},
        "tags": ["pyq", "cdp", "prt_2019"]
    },
    {
        "id": "PYQ-69K-003",
        "exam": "UP_PRT",
        "subject": "General Knowledge",
        "chapter": "Modern India",
        "topic": "Bhartendu Harishchandra",
        "difficulty": "easy",
        "questionType": "mcq",
        "question": "Who edited the famous Hindi literary journal 'Kavi Vachan Sudha' published from Kashi (Varanasi)?",
        "hindiQuestion": "काशी (वाराणसी) से प्रकाशित होने वाली प्रसिद्ध पत्रिका 'कविवचन सुधा' के संपादक कौन थे?",
        "options": ["Bhartendu Harishchandra", "Mahavir Prasad Dwivedi", "Pratap Narayan Mishra", "Bal Krishna Bhatt"],
        "hindiOptions": ["भारतेन्दु हरिश्चंद्र", "महावीर प्रसाद द्विवेदी (सरस्वती)", "प्रतापनारायण मिश्र (ब्राह्मण)", "बालकृष्ण भट्ट (हिन्दी प्रदीप)"],
        "answer": 0,
        "explanation": "Bhartendu Harishchandra started publishing 'Kavi Vachan Sudha' in 1868 from Kashi.",
        "hindiExplanation": "भारतेन्दु हरिश्चंद्र ने 1868 ई. में काशी से 'कविवचन सुधा' का संपादन प्रारंभ किया था।",
        "sourceType": "pyq",
        "pyqDetails": {"examName": "UP 69,000 Assistant Teacher", "year": 2019, "paper": "General Paper", "officialAnswerKeyRef": "Official Key Q14"},
        "tags": ["pyq", "gk", "prt_2019"]
    },
    {
        "id": "PYQ-69K-004",
        "exam": "UP_PRT",
        "subject": "Science",
        "chapter": "Physics",
        "topic": "Lenses & Optics",
        "difficulty": "medium",
        "questionType": "numerical",
        "question": "What is the power of a convex lens having a focal length of 50 cm?",
        "hindiQuestion": "50 सेमी फोकस दूरी वाले उत्तल लेंस की क्षमता (Power) कितनी होगी?",
        "options": ["+2.0 Dioptre", "-2.0 Dioptre", "+0.5 Dioptre", "+5.0 Dioptre"],
        "hindiOptions": ["+2.0 डायोप्टर", "-2.0 डायोप्टर", "+0.5 डायोप्टर", "+5.0 डायोप्टर"],
        "answer": 0,
        "explanation": "P = 1 / f(in meters). f = 50 cm = 0.5 m. Power = 1 / 0.5 = +2.0 D (positive for convex lens).",
        "hindiExplanation": "लेंस की क्षमता P = 100 / f(सेमी) = 100 / 50 = +2D (उत्तल लेंस की क्षमता धनात्मक होती है)।",
        "sourceType": "pyq",
        "pyqDetails": {"examName": "UP 69,000 Assistant Teacher", "year": 2019, "paper": "General Paper", "officialAnswerKeyRef": "Official Key Q87"},
        "tags": ["pyq", "science", "prt_2019"]
    },
    {
        "id": "PYQ-69K-005",
        "exam": "UP_PRT",
        "subject": "Mathematics",
        "chapter": "Geometry",
        "topic": "Angles",
        "difficulty": "easy",
        "questionType": "numerical",
        "question": "If two complementary angles are in the ratio 2:3, what is the measure of the smaller angle?",
        "hindiQuestion": "यदि दो पूरक (कोटिपूरक) कोण 2:3 के अनुपात में हैं, तो छोटे कोण का मान क्या होगा?",
        "options": ["36 degrees", "54 degrees", "45 degrees", "30 degrees"],
        "hindiOptions": ["36°", "54°", "45°", "30°"],
        "answer": 0,
        "explanation": "Complementary angles sum to 90 degrees. 2x + 3x = 90 => 5x = 90 => x = 18. Smaller angle = 2 * 18 = 36 degrees.",
        "hindiExplanation": "कोटिपूरक कोणों का योग 90° होता है। 2x + 3x = 90 => 5x = 90 => x = 18°। छोटा कोण = 2 × 18 = 36°।",
        "sourceType": "pyq",
        "pyqDetails": {"examName": "UP 69,000 Assistant Teacher", "year": 2019, "paper": "General Paper", "officialAnswerKeyRef": "Official Key Q99"},
        "tags": ["pyq", "math", "prt_2019"]
    },

    # UP TGT 2021 Questions
    {
        "id": "PYQ-TGT-HIN-001",
        "exam": "UP_TGT",
        "subject": "Hindi",
        "chapter": "Bhaktikal",
        "topic": "Surdas",
        "difficulty": "medium",
        "questionType": "mcq",
        "question": "In which dialect (Boli) of Hindi did Mahakavi Surdas compose his immortal work 'Sursagar'?",
        "hindiQuestion": "महाकवि सूरदास ने अपने अमर ग्रंथ 'सूरसागर' की रचना किस भाषा/बोली में की?",
        "options": ["Braj Bhasha (ब्रजभाषा)", "Awadhi", "Maithili", "Khari Boli"],
        "hindiOptions": ["ब्रजभाषा", "अवधी", "मैथिली", "खड़ी बोली"],
        "answer": 0,
        "explanation": "Surdas, the foremost poet of the Ashtachhap, composed Sursagar, Sur Saravali, and Sahitya Lahari in melodious Braj Bhasha.",
        "hindiExplanation": "अष्टछाप के प्रमुख कवि सूरदास ने वात्सल्य और श्रृंगार से परिपूर्ण रचनाएं ठेठ ब्रजभाषा में कीं।",
        "sourceType": "pyq",
        "pyqDetails": {"examName": "UP TGT Hindi", "year": 2021, "paper": "Subject Paper", "officialAnswerKeyRef": "Key Q28"},
        "tags": ["pyq", "tgt_hindi", "bhaktikal"]
    },
    {
        "id": "PYQ-TGT-ENG-001",
        "exam": "UP_TGT",
        "subject": "English Language & Literature",
        "chapter": "William Shakespeare",
        "topic": "Tragedies",
        "difficulty": "medium",
        "questionType": "mcq",
        "question": "Which of the following is considered William Shakespeare's longest play?",
        "hindiQuestion": "विलियम शेक्सपियर का सबसे लंबा नाटक कौन सा माना जाता है?",
        "options": ["Hamlet", "Macbeth", "King Lear", "Othello"],
        "hindiOptions": ["हैमलेट (Hamlet)", "मैकबेथ", "किंग लियर", "ओथेलो"],
        "answer": 0,
        "explanation": "'Hamlet' (The Tragedy of Hamlet, Prince of Denmark) contains 4,042 lines and roughly 30,000 words, making it Shakespeare's longest play.",
        "hindiExplanation": "'हैमलेट' शेक्सपियर की सबसे लम्बी नाट्य रचना है, जिसमें 4,000 से अधिक पंक्तियां हैं।",
        "sourceType": "pyq",
        "pyqDetails": {"examName": "UP TGT English", "year": 2021, "paper": "Subject Paper", "officialAnswerKeyRef": "Key Q51"},
        "tags": ["pyq", "tgt_english", "shakespeare"]
    },
    {
        "id": "PYQ-TGT-MAT-001",
        "exam": "UP_TGT",
        "subject": "Mathematics",
        "chapter": "Coordinate Geometry",
        "topic": "Conic Sections",
        "difficulty": "hard",
        "questionType": "conceptual",
        "question": "What is the eccentricity (e) of a parabola in coordinate geometry?",
        "hindiQuestion": "निर्देशांक ज्यामिति में किसी परवलय (Parabola) की उत्केन्द्रता (Eccentricity - e) का मान क्या होता है?",
        "options": ["e = 1", "e < 1 (Ellipse)", "e > 1 (Hyperbola)", "e = 0 (Circle)"],
        "hindiOptions": ["e = 1", "e < 1 (दीर्घवृत्त)", "e > 1 (अतिपरवलय)", "e = 0 (वृत्त)"],
        "answer": 0,
        "explanation": "A conic section is a parabola if and only if eccentricity e = 1 (distance from focus equals distance from directrix).",
        "hindiExplanation": "परवलय के लिए नाभि से दूरी और नियता से दूरी का अनुपात सदैव 1 होता है (e = 1)।",
        "sourceType": "pyq",
        "pyqDetails": {"examName": "UP TGT Mathematics", "year": 2021, "paper": "Subject Paper", "officialAnswerKeyRef": "Key Q72"},
        "tags": ["pyq", "tgt_math", "conics"]
    },

    # UPTET 2021 Questions
    {
        "id": "PYQ-UPTET-2021-001",
        "exam": "UPTET",
        "subject": "Child Development",
        "chapter": "Growth & Development",
        "topic": "Principles of Development",
        "difficulty": "easy",
        "questionType": "mcq",
        "question": "Which principle states that motor development proceeds from head to toe?",
        "hindiQuestion": "विकास का कौन सा सिद्धांत बताता है कि गामक विकास सिर से पैर की ओर अग्रसर होता है?",
        "options": ["Cephalocaudal Principle (मस्तकाधोमुखी सिद्धांत)", "Proximodistal Principle (समीप-दूराभिमुख)", "Principle of Interrelation", "Principle of Spiral Development"],
        "hindiOptions": ["मस्तकाधोमुखी सिद्धांत (Cephalocaudal)", "समीप-दूराभिमुख सिद्धांत", "परस्पर संबंध का सिद्धांत", "वर्तुलाकार विकास का सिद्धांत"],
        "answer": 0,
        "explanation": "Cephalocaudal principle dictates that control and muscular coordination progress from head downward toward the trunk and feet.",
        "hindiExplanation": "मस्तकाधोमुखी (Cephalocaudal) क्रम में शिशु सर्वप्रथम अपने सिर पर, फिर धड़ और अंत में पैरों पर नियंत्रण सीखता है।",
        "sourceType": "pyq",
        "pyqDetails": {"examName": "UPTET Paper-1", "year": 2021, "paper": "Child Development Section", "officialAnswerKeyRef": "Official Key Q01"},
        "tags": ["pyq", "uptet", "cdp"]
    },
    {
        "id": "PYQ-UPTET-2021-002",
        "exam": "UPTET",
        "subject": "Environmental Studies (EVS)",
        "chapter": "Ecology & Wildlife",
        "topic": "Wildlife Protection",
        "difficulty": "easy",
        "questionType": "mcq",
        "question": "In which year was the 'Wildlife Protection Act' enacted in India?",
        "hindiQuestion": "भारत में 'वन्यजीव संरक्षण अधिनियम' किस वर्ष लागू किया गया था?",
        "options": ["1972", "1980 (Forest Act)", "1986 (Environment Act)", "1974 (Water Act)"],
        "hindiOptions": ["1972 ई.", "1980 ई.", "1986 ई.", "1974 ई."],
        "answer": 0,
        "explanation": "The Wildlife Protection Act was passed by the Parliament of India in 1972 to protect plant and animal species.",
        "hindiExplanation": "वन्यजीवों के शिकार और अवैध व्यापार की रोकथाम हेतु 1972 में वन्यजीव संरक्षण अधिनियम पारित किया गया।",
        "sourceType": "pyq",
        "pyqDetails": {"examName": "UPTET Paper-1", "year": 2021, "paper": "EVS Section", "officialAnswerKeyRef": "Official Key Q121"},
        "tags": ["pyq", "uptet", "evs"]
    }
]

with open('src/data/pyqs.json', 'r', encoding='utf-8') as f:
    existing_pyqs = json.load(f)

existing_pyqs.extend(pyqs_add)

with open('src/data/pyqs.json', 'w', encoding='utf-8') as f:
    json.dump(existing_pyqs, f, ensure_ascii=False, indent=2)

print(f"Updated pyqs.json to {len(existing_pyqs)} items!")
